SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE VIEW [Landing].[MYSOLUTION_GenericAttributeView]
AS
WITH TableData
AS (
    SELECT
        Id,
        CONVERT(VARBINARY(20), HASHBYTES('MD5', CONCAT(
            Id,
            ' '
        ))) AS HistoricalHashKey,
        CONVERT(VARBINARY(20), HASHBYTES('MD5', CONCAT(
            EntityId,
            [Key],
            Value,
            ' '
        ))) AS ChangeHashKey,
        CURRENT_TIMESTAMP AS InsertDatetime,
        CURRENT_TIMESTAMP AS UpdateDatetime,
        EntityId,
        [Key],
        Value

    FROM MYSOLUTION.GenericAttribute
    WHERE [Key] IN
    (
        N'Cellulare',
        N'City',
        N'CodiceFiscale',
        N'Company',
        N'FirstName',
        N'LastName',
        N'Phone',
        N'StreetAddress',
        N'VatNumber',
        N'ZipPostalCode',
        N'CountryId',
        N'StateProvinceId'

        --N' ProfessionId',
        --N'AccountActivationToken',
        --N'AllSettingsPage.HideSearchBlock',
        --N'CatalogSettingsPage.HideTagsBlock',
        --N'category-advanced-mode',
        --N'CategoryPage.HideDisplayBlock',
        --N'CategoryPage.HideInfoBlock',
        --N'CategoryPage.HideMappingsBlock',
        --N'CategoryPage.HideProductsBlock',
        --N'CategoryPage.HideSEOBlock',
        --N'checkoutattribute-advanced-mode',
        --N'CodiceCIG',
        --N'CodiceIPA',
        --N'CodiceSDI',
        --N'CountryPage.HideStatesBlock',
        --N'CurrencyId',
        --N'CustomerListPage.HideSearchBlock',
        --N'CustomerPage.HideActivityLogBlock',
        --N'CustomerPage.HideAddressesBlock',
        --N'CustomerPage.HideBackInStockSubscriptionsBlock',
        --N'CustomerPage.HideInfoBlock',
        --N'CustomerPage.HideOrdersBlock',
        --N'CustomerPage.HidePlaceOrderBlock',
        --N'CustomerPage.HideShoppingCartAndWishlistBlock',
        --N'CustomerTypeId',
        --N'CustomerUserSettingsPage.HideAccountBlock',
        --N'CustomerUserSettingsPage.HideAddressFormFieldsBlock',
        --N'CustomerUserSettingsPage.HideCustomerFormFieldsBlock',
        --N'CustomerUserSettingsPage.HideProfileBlock',
        --N'CustomerUserSettingsPage.HideSecurityBlock',
        --N'DateOfBirth',
        --N'DiscountCouponCode',
        --N'DiscountPage.HideAppliedToProductsBlock',
        --N'DiscountPage.HideInfoBlock',
        --N'DiscountPage.HideRequirementsBlock',
        --N'DiscountPage.HideUsageHistoryBlock',
        --N'EmailPec',
        --N'EuCookieLaw.Accepted',
        --N'Gender',
        --N'GeneralCommonSettingsPage.HideAdminAreaBlock',
        --N'GiftCardCouponCodes',
        --N'GiftCardPage.HideUsageHistoryBlock',
        --N'HideCommonStatisticsPanel',
        --N'HideNopCommerceNewsPanel',
        --N'HideSidebar',
        --N'LanguageId',
        --N'LanguagePage.HideResourcesBlock',
        --N'LastContinueShoppingPage',
        --N'manufacturer-advanced-mode',
        --N'ManufacturersPage.HideSearchBlock',
        --N'messagetemplate-advanced-mode',
        --N'NewsItemPage.HideSeoBlock',
        --N'OfferedShippingOptions',
        --N'OrderPage.HideBillingAndShippingBlock',
        --N'OrderPage.HideInfoBlock',
        --N'OrderPage.HideProductsBlock',
        --N'OrderSettingsPage.HideGiftCardsBlock',
        --N'OrdersPage.HideSearchBlock',
        --N'PasswordRecoveryToken',
        --N'PasswordRecoveryTokenDateGenerated',
        --N'product-advanced-mode',
        --N'ProductAttributeMappingPage.HideCommonBlock',
        --N'ProductAttributeMappingPage.HideValuesBlock',
        --N'ProductAttributePage.HidePredefinedValuesBlock',
        --N'ProductAttributePage.HideUsedByProductsBlock',
        --N'ProductImageProportionCss-SevenSpikes.Theme.Prisma',
        --N'ProductListPage.HideSearchBlock',
        --N'ProductPage.HideCourseBlock',
        --N'ProductPage.HideCrossSellsProductsBlock',
        --N'ProductPage.HideDownloadableBlock',
        --N'ProductPage.HideGiftCardBlock',
        --N'ProductPage.HideInfoBlock',
        --N'ProductPage.HideInventoryBlock',
        --N'ProductPage.HidePicturesBlock',
        --N'ProductPage.HidePricesBlock',
        --N'ProductPage.HideProductAttributesBlock',
        --N'ProductPage.HidePurchasedWithOrdersBlock',
        --N'ProductPage.HideRecurringBlock',
        --N'ProductPage.HideRelatedProductsBlock',
        --N'ProductPage.HideRentalBlock',
        --N'ProductPage.HideSEOBlock',
        --N'ProductPage.HideShippingBlock',
        --N'ProductPage.HideSpecificationAttributeBlock',
        --N'ProductPage.HideStockQuantityHistoryBlock',
        --N'ProductPage.SS.Attachments',
        --N'ProfessionDetailId',
        --N'QueuedEmailsPage.HideSearchBlock',
        --N'Reports.HideBestsellersBriefReportByAmountPanel',
        --N'Reports.HideBestsellersBriefReportByQuantityPanel',
        --N'Reports.HideCustomerStatisticsPanel',
        --N'Reports.HideLatestOrdersPanel',
        --N'Reports.HideOrderAverageReportPanel',
        --N'Reports.HideOrderIncompleteReportPanel',
        --N'Reports.HideOrderStatisticsPanel',
        --N'Reports.HidePopularSearchTermsReport',
        --N'SelectedPaymentMethod',
        --N'SelectedShippingOption',
        --N'settings-advanced-mode',
        --N'ShoppingCartSettingsPage.HideCommonBlock',
        --N'ShoppingCartSettingsPage.HideMiniShoppingCartBlock',
        --N'SpecificationAttributePage.HideInfoBlock',
        --N'SpecificationAttributePage.HideOptionsBlock',
        --N'SpecificationAttributePage.HideUsedByProductsBlock',
        --N'SplitPayment',
        --N'store-advanced-mode',
        --N'StreetAddress2',
        --N'topic-advanced-mode',
        --N'TopicDetailsPage.HideDisplayBlock',
        --N'TopicDetailsPage.HideInfoBlock',
        --N'TopicDetailsPage.HideSeoBlock',
        --N'TopicsPage.HideSearchBlock',
        --N'UseRewardPointsDuringCheckout',
        --N'VatNumberStatusId',
        --N'vendor-advanced-mode',
    )
)
SELECT
    -- Chiavi
    TD.Id,

    -- Campi per sincronizzazione
    TD.HistoricalHashKey,
    TD.ChangeHashKey,
    CONVERT(VARCHAR(34), TD.HistoricalHashKey, 1) AS HistoricalHashKeyASCII,
    CONVERT(VARCHAR(34), TD.ChangeHashKey, 1) AS ChangeHashKeyASCII,
    TD.InsertDatetime,
    TD.UpdateDatetime,
    CAST(0 AS BIT) AS IsDeleted,

    -- Attributi
    TD.EntityId,
    TD.[Key],
    TD.Value

FROM TableData TD;
GO
