CREATE TABLE [Import].[Dates]
(
[DateKey] [int] NOT NULL,
[Date] [date] NULL,
[FullDateUK] [char] (10) COLLATE Latin1_General_CI_AS NULL,
[FullDateUSA] [char] (10) COLLATE Latin1_General_CI_AS NULL,
[DayOfMonth] [varchar] (2) COLLATE Latin1_General_CI_AS NULL,
[DaySuffix] [varchar] (4) COLLATE Latin1_General_CI_AS NULL,
[DayName] [varchar] (9) COLLATE Latin1_General_CI_AS NULL,
[DayOfWeekUSA] [char] (1) COLLATE Latin1_General_CI_AS NULL,
[DayOfWeekUK] [char] (1) COLLATE Latin1_General_CI_AS NULL,
[DayOfWeekInMonth] [varchar] (2) COLLATE Latin1_General_CI_AS NULL,
[DayOfWeekInYear] [varchar] (2) COLLATE Latin1_General_CI_AS NULL,
[DayOfQuarter] [varchar] (3) COLLATE Latin1_General_CI_AS NULL,
[DayOfYear] [varchar] (3) COLLATE Latin1_General_CI_AS NULL,
[WeekOfMonth] [varchar] (1) COLLATE Latin1_General_CI_AS NULL,
[WeekOfQuarter] [varchar] (2) COLLATE Latin1_General_CI_AS NULL,
[WeekOfYear] [varchar] (2) COLLATE Latin1_General_CI_AS NULL,
[Month] [varchar] (2) COLLATE Latin1_General_CI_AS NULL,
[MonthName] [varchar] (9) COLLATE Latin1_General_CI_AS NULL,
[MonthOfQuarter] [varchar] (2) COLLATE Latin1_General_CI_AS NULL,
[Quarter] [char] (1) COLLATE Latin1_General_CI_AS NULL,
[QuarterName] [varchar] (9) COLLATE Latin1_General_CI_AS NULL,
[Year] [char] (4) COLLATE Latin1_General_CI_AS NULL,
[YearName] [char] (7) COLLATE Latin1_General_CI_AS NULL,
[MonthYear] [char] (10) COLLATE Latin1_General_CI_AS NULL,
[MMYYYY] [char] (6) COLLATE Latin1_General_CI_AS NULL,
[FirstDayOfMonth] [date] NULL,
[LastDayOfMonth] [date] NULL,
[FirstDayOfQuarter] [date] NULL,
[LastDayOfQuarter] [date] NULL,
[FirstDayOfYear] [date] NULL,
[LastDayOfYear] [date] NULL,
[IsHolidayUSA] [bit] NULL,
[IsWeekday] [bit] NULL,
[HolidayUSA] [varchar] (50) COLLATE Latin1_General_CI_AS NULL,
[IsHolidayUK] [bit] NULL,
[HolidayUK] [varchar] (50) COLLATE Latin1_General_CI_AS NULL,
[DayNameIT] [varchar] (9) COLLATE Latin1_General_CI_AS NULL,
[MonthNameIT] [varchar] (9) COLLATE Latin1_General_CI_AS NULL,
[IsHolidayIT] [bit] NULL,
[HolidayIT] [varchar] (50) COLLATE Latin1_General_CI_AS NULL,
[FullDateIT] [char] (10) COLLATE Latin1_General_CI_AS NULL
) ON [PRIMARY]
GO
ALTER TABLE [Import].[Dates] ADD CONSTRAINT [PK_Import_Dates] PRIMARY KEY CLUSTERED  ([DateKey]) ON [PRIMARY]
GO
