CREATE TABLE [Staging].[Documenti]
(
[IDDocumento_Riga] [int] NOT NULL,
[HistoricalHashKey] [varbinary] (20) NULL,
[ChangeHashKey] [varbinary] (20) NULL,
[HistoricalHashKeyASCII] [varchar] (34) COLLATE Latin1_General_CI_AS NULL,
[ChangeHashKeyASCII] [varchar] (34) COLLATE Latin1_General_CI_AS NULL,
[InsertDatetime] [datetime] NOT NULL,
[UpdateDatetime] [datetime] NOT NULL,
[IsDeleted] [int] NOT NULL,
[IDDocumento] [int] NOT NULL,
[IDProfilo] [nvarchar] (10) COLLATE Latin1_General_CI_AS NOT NULL,
[Profilo] [nvarchar] (60) COLLATE Latin1_General_CI_AS NOT NULL,
[TipoRegistro] [char] (2) COLLATE Latin1_General_CI_AS NOT NULL,
[NumeroRegistro] [int] NOT NULL,
[Registro] [nvarchar] (60) COLLATE Latin1_General_CI_AS NOT NULL,
[CodiceEsercizio] [char] (4) COLLATE Latin1_General_CI_AS NOT NULL,
[PKDataInizioEsercizio] [date] NOT NULL,
[PKDataFineEsercizio] [date] NOT NULL,
[PKDataRegistrazione] [date] NOT NULL,
[NumeroDocumento] [nvarchar] (20) COLLATE Latin1_General_CI_AS NOT NULL,
[PKDataDocumento] [date] NOT NULL,
[PKDataCompetenza] [date] NOT NULL,
[TipoSoggettoCommerciale] [nvarchar] (10) COLLATE Latin1_General_CI_AS NOT NULL,
[PKCliente] [int] NOT NULL,
[TipoSoggettoCommercialeFattura] [nvarchar] (10) COLLATE Latin1_General_CI_AS NOT NULL,
[PKClienteFattura] [int] NOT NULL,
[PKGruppoAgenti] [int] NOT NULL,
[PKCapoArea] [int] NOT NULL,
[PKDataFineContratto] [date] NOT NULL,
[Libero4] [nvarchar] (200) COLLATE Latin1_General_CI_AS NOT NULL,
[PKDataInizioContratto] [date] NOT NULL,
[IDLibero1] [nvarchar] (10) COLLATE Latin1_General_CI_AS NOT NULL,
[Libero1] [nvarchar] (60) COLLATE Latin1_General_CI_AS NOT NULL,
[IDLibero2] [nvarchar] (10) COLLATE Latin1_General_CI_AS NOT NULL,
[Libero2] [nvarchar] (60) COLLATE Latin1_General_CI_AS NOT NULL,
[IDLibero3] [nvarchar] (10) COLLATE Latin1_General_CI_AS NOT NULL,
[Libero3] [nvarchar] (60) COLLATE Latin1_General_CI_AS NOT NULL,
[IDTipoFatturazione] [nvarchar] (10) COLLATE Latin1_General_CI_AS NOT NULL,
[TipoFatturazione] [nvarchar] (60) COLLATE Latin1_General_CI_AS NOT NULL,
[PKGruppoAgenti_Riga] [int] NOT NULL,
[PKCapoArea_Riga] [int] NOT NULL,
[NumeroRiga] [int] NOT NULL,
[PKArticolo] [int] NOT NULL,
[CodiceCondizioniPagamento] [nvarchar] (10) COLLATE Latin1_General_CI_AS NULL,
[CondizioniPagamento] [nvarchar] (60) COLLATE Latin1_General_CI_AS NULL,
[RinnovoAutomatico] [char] (1) COLLATE Latin1_General_CI_AS NOT NULL,
[NoteIntestazione] [nvarchar] (1000) COLLATE Latin1_General_CI_AS NOT NULL,
[IsProfiloValidoPerStatisticaFatturato] [bit] NOT NULL,
[IsProfiloValidoPerStatisticaFatturatoFormazione] [bit] NOT NULL,
[PKMacroTipologia] [int] NOT NULL,
[ImportoTotale] [decimal] (10, 2) NOT NULL,
[ImportoProvvigioneCapoArea] [decimal] (10, 2) NOT NULL,
[ImportoProvvigioneAgente] [decimal] (10, 2) NOT NULL,
[ImportoProvvigioneSubagente] [decimal] (10, 2) NOT NULL,
[Progressivo] [int] NOT NULL,
[Quote] [int] NOT NULL,
[IDDocumento_Riga_Provenienza] [int] NULL,
[NoteDecisionali] [nvarchar] (1000) COLLATE Latin1_General_CI_AS NOT NULL,
[PKDataDisdetta] [date] NOT NULL,
[IDDocumentoRinnovato] [int] NULL
) ON [PRIMARY]
GO
ALTER TABLE [Staging].[Documenti] ADD CONSTRAINT [PK_Staging_Documenti] PRIMARY KEY CLUSTERED ([UpdateDatetime], [IDDocumento_Riga]) ON [PRIMARY]
GO
CREATE UNIQUE NONCLUSTERED INDEX [IX_Staging_Documenti_BusinessKey] ON [Staging].[Documenti] ([IDDocumento_Riga]) ON [PRIMARY]
GO
